services:
  db:
    image: postgres:16.4-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: /bin/sh -c "npm install && npm start"
    depends_on:
      - db
    ports:
      - "3000:3000"
